In [ ]:
""" when we need to work with the numerical operations using the python there are only few operations tht we can perform using the python.
    sometimes it is little complexity.soo In python they have introduced the numpy library by using the numpy library we can perform the numerical
    operations very easily .mainly the numpy will also supports the array's."""

In [1]:
#In generally we can't perform the numerical operations on the list of elements at a time.but by using numpy we can do that.
li=[1,2,3,4,5]
print(li/2)

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [2]:
"""by using the numpy we can do that"""
import numpy as np
data=np.array([1,2,3,4,5])
print(data/2)

[0.5 1.  1.5 2.  2.5]


In [6]:
#one dimensional array creation
import numpy as np
data=np.array([1,2,3,4,5])
print(data)
print(data[-1])
print(type(data))
print(np.shape(data))
print(data.dtype)

[1 2 3 4 5]
5
<class 'numpy.ndarray'>
(5,)
int32


In [15]:
#two dimensional array creation
data=np.array([[45,56,34],[54,34,12],[78,67,46]])
print(data)
print(data[1:,1:])

[[45 56 34]
 [54 34 12]
 [78 67 46]]
[[34 12]
 [67 46]]


In [7]:
#three dimensional array
data=np.array([[[12,23,12],[34,45,12],[32,56,14]],[[23,12,35],[78,89,56],[67,80,65]]])
print(data)

[[[12 23 12]
  [34 45 12]
  [32 56 14]]

 [[23 12 35]
  [78 89 56]
  [67 80 65]]]


In [8]:
#to know which data type it is
print(type(data))

<class 'numpy.ndarray'>


In [9]:
#to konw number of dimensions that the given array cotains
print(data.ndim)

3


In [10]:
#to get the random elements numpy contains random module.
x=np.random.randint(1,10,3)
print(x)

[9 2 3]


In [11]:
# to get the random integers in the matrix format
x=np.random.randint(1,100,(4,4))
print(x)

[[67 93 81 64]
 [10 88 28 71]
 [58 76 38 55]
 [75 65 79 80]]


In [16]:
# to get the random float value between 0,1
x=np.random.rand()
print(x)

0.9103579777287414


In [18]:
x=np.zeros((2,3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [20]:
x=np.ones((4,5))
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [21]:
x=np.full((3,3),6)
print(x)

[[6 6 6]
 [6 6 6]
 [6 6 6]]


In [24]:
data=np.arange(0,100,5)
print(data)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [25]:
data=np.arange(20,50,5)
print(data)


[20 25 30 35 40 45]


In [27]:
data=np.linspace(0,10,4)
print(data)

[ 0.          3.33333333  6.66666667 10.        ]


In [28]:
dt=np.array([1,2,3,4,5])
print(sum(dt))

15


In [2]:
import numpy as np
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [5]:
x=np.array([[34,45,23],[78,56,34],[67,12,89]])
x.shape=(9,1)
print(x)

[[34]
 [45]
 [23]
 [78]
 [56]
 [34]
 [67]
 [12]
 [89]]


In [6]:
print(x.sum())

438


In [7]:
print(x.mean())

48.666666666666664


In [13]:
da=np.array([1,2,3,4,5])
print(np.median(da))

3.0


In [16]:
print(np.max(da))

5


In [17]:
print(np.max(x))

89


In [18]:
print(np.min(da))

1


In [19]:
print(np.min(x))

12


In [8]:
array1=np.array([[1,2,3],[4,5,6],[5,6,7]])
print(array1)
array2=np.array([[34,56,45],[23,41,23],[56,78,89]])
print(array2)

[[1 2 3]
 [4 5 6]
 [5 6 7]]
[[34 56 45]
 [23 41 23]
 [56 78 89]]


In [9]:
print(array1+array2)

[[35 58 48]
 [27 46 29]
 [61 84 96]]


In [15]:
print(np.sum((array1,array2),axis=0))

[[35 58 48]
 [27 46 29]
 [61 84 96]]


In [18]:
print(np.min((array1,array2),axis=0))

[[1 2 3]
 [4 5 6]
 [5 6 7]]


In [19]:
print(np.max((array1,array2),axis=0))

[[34 56 45]
 [23 41 23]
 [56 78 89]]


In [20]:
print(np.mean((array1,array2),axis=0))

[[17.5 29.  24. ]
 [13.5 23.  14.5]
 [30.5 42.  48. ]]


In [21]:
print(np.median((array1,array2),axis=0))

[[17.5 29.  24. ]
 [13.5 23.  14.5]
 [30.5 42.  48. ]]


In [22]:
print(array1-array2)

[[-33 -54 -42]
 [-19 -36 -17]
 [-51 -72 -82]]


In [23]:
print(array1*array2)

[[ 34 112 135]
 [ 92 205 138]
 [280 468 623]]


In [24]:
print(array1/array2)

[[0.02941176 0.03571429 0.06666667]
 [0.17391304 0.12195122 0.26086957]
 [0.08928571 0.07692308 0.07865169]]


In [28]:
print(np.subtract(30,45))

-15


In [30]:
print(np.multiply(30,40))

1200


In [31]:
print(np.equal(array1,array2))

[[False False False]
 [False False False]
 [False False False]]


In [32]:
print(np.dot(array1,array2))

[[ 248  372  358]
 [ 587  897  829]
 [ 700 1072  986]]


In [39]:
#string functions
x=np.array([3,4,5,1,"data","engineering"])
print(np.char.lower(x))
print(np.char.upper(x))
print(np.char.swapcase(x))
print(np.char.capitalize(x))
print(np.char.title(x))
print(np.char.startswith(x,"d"))
print(np.char.endswith(x,"d"))
print(np.char.count(x,"d"))
print(np.char.split(x,"a"))
print(np.char.center(x,20,fillchar="#"))
print(np.char.ljust(x,20,fillchar="#"))
print(np.char.rjust(x,20,fillchar="#"))
print(np.char.find(x,"1"))

['3' '4' '5' '1' 'data' 'engineering']
['3' '4' '5' '1' 'DATA' 'ENGINEERING']
['3' '4' '5' '1' 'DATA' 'ENGINEERING']
['3' '4' '5' '1' 'Data' 'Engineering']
['3' '4' '5' '1' 'Data' 'Engineering']
[False False False False  True False]
[False False False False False False]
[0 0 0 0 1 0]
[list(['3']) list(['4']) list(['5']) list(['1']) list(['d', 't', ''])
 list(['engineering'])]
['#########3##########' '#########4##########' '#########5##########'
 '#########1##########' '########data########' '####engineering#####']
['3###################' '4###################' '5###################'
 '1###################' 'data################' 'engineering#########']
['###################3' '###################4' '###################5'
 '###################1' '################data' '#########engineering']
[-1 -1 -1  0 -1 -1]


In [42]:
#trignometry functions
data=np.array([1,2,3,4,5])
print(np.exp(data))
print(np.sqrt(data))
print(np.log(data))
print(np.sin(data))
print(np.cos(data))
print(np.tan(data))

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[1.         1.41421356 1.73205081 2.         2.23606798]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501]


In [44]:
#descripitive statistics
data=np.array([67,78,45,23,45,89])
print(np.mean(data))
print(np.median(data))
print(np.sum(data))
print(np.std(data))
print(np.corrcoef(data))
q1=np.quantile(data,0.25)
q2=np.quantile(data,0.50)
q3=np.quantile(data,0.75)
q4=np.quantile(data,1)
qd=(q3-q1)/(q3+q1)
print(qd)

57.833333333333336
56.0
347
22.37868529551179
1.0
0.2515592515592516


In [47]:
arr=np.array([[1,2,3,4],[5,6,7,8],[3,4,2,1],[5,2,4,8]])
print(np.split(arr,2,axis=0))
print(np.split(arr,2,axis=1))
print(np.hsplit(arr,2))
print(np.vsplit(arr,2))
print(arr.T)

[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[3, 4, 2, 1],
       [5, 2, 4, 8]])]
[array([[1, 2],
       [5, 6],
       [3, 4],
       [5, 2]]), array([[3, 4],
       [7, 8],
       [2, 1],
       [4, 8]])]
[array([[1, 2],
       [5, 6],
       [3, 4],
       [5, 2]]), array([[3, 4],
       [7, 8],
       [2, 1],
       [4, 8]])]
[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[3, 4, 2, 1],
       [5, 2, 4, 8]])]
[[1 5 3 5]
 [2 6 4 2]
 [3 7 2 4]
 [4 8 1 8]]


In [53]:
#boardcasting
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2=np.array([[4],[5],[6]])
print(arr-arr2)

[[-3 -2 -1]
 [-1  0  1]
 [ 1  2  3]]


In [54]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [68]:
arr=np.array([[34,45,12,34],[56,12,23,45],[78,90,89,67],[45,13,25,43]])
array1=arr.ravel()
print(array1.reshape((8,2)))
arr.shape=(8,2)
print(arr)

[[34 45]
 [12 34]
 [56 12]
 [23 45]
 [78 90]
 [89 67]
 [45 13]
 [25 43]]
[[34 45]
 [12 34]
 [56 12]
 [23 45]
 [78 90]
 [89 67]
 [45 13]
 [25 43]]


In [70]:
array1=np.array([[1,2,3],[4,5,6],[5,6,7]])
array2=np.array([[34,56,45],[23,41,23],[56,78,89]])
print(np.concatenate([array1,array2],axis=0))
print(np.concatenate([array1,array2],axis=1))

[[ 1  2  3]
 [ 4  5  6]
 [ 5  6  7]
 [34 56 45]
 [23 41 23]
 [56 78 89]]
[[ 1  2  3 34 56 45]
 [ 4  5  6 23 41 23]
 [ 5  6  7 56 78 89]]


In [ ]:
print(np.vstack([array1,array2]))
print(np.stack([array1,array2]))