In [ ]:
"""Problem Statement:
You work in XYZ Corporation as a Data Analyst. Your corporation has told you to
use the NumPy package and do some tasks related to that."""


In [1]:
#Tasks To Be Performed:
#1. Create a 3x3 matrix array with values ranging from 2 to 10.
import numpy as np
data=np.random.randint(2,10,(3,3))
print(data)

[[4 4 5]
 [5 8 6]
 [8 5 5]]


In [8]:
"""2. Create a NumPy array having user input values and convert the integer
type to the float type of the elements of the array. For instance: Original
array [1, 2, 3, 4] Array converted to a float type: [ 1. 2. 3. 4.]"""
import numpy as np
arr=list(map(int,input().split()))
nu_array=np.array(arr)
print(nu_array)
print(type(nu_array))
print(nu_array.astype(float))


 1 2 3 4 5


[1 2 3 4 5]
<class 'numpy.ndarray'>
['1' '2' '3' '4' '5']


In [15]:
"""3. Write a NumPy program to append values to the end of an array. For
instance: Original array: [10, 20, 30] . After that, append values to the end
of the array: [10 20 30 40 50 60 70 80 90]"""
array=list(map(int,input().split()))
arr1=np.array(array)
num=list(map(int,input().split()))
num=np.array(num)
np.append(arr1,num)

 10 20 30
 40 50 60 70 80 90


array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [16]:
"""4. Create two NumPy arrays and add the elements of both the arrays and
store the result in sumArray."""
np_arr1=list(map(int,input().split()))
np_arr1=np.array(np_arr1)
np_arr2=list(map(int,input().split()))
np_arr2=np.array(np_arr2)
sumArray=np_arr1+np_arr2
print(sumArray)

 10 20 30 40
 50 60 70 80


[ 60  80 100 120]


In [24]:
"""5. Create a 3x3 array having values from 10-90 (interval of 10) and store that
in array1
Perform the following tasks:
a. Extract the 1st row from the array
b. Extract the last element from the array"""
array1=np.arange(10,100,10)
array1.shape=(3,3)
print(array1)
print(array1[0,0:])
print(array1[2,2])

[[10 20 30]
 [40 50 60]
 [70 80 90]]
[10 20 30]
90
